ekf_filter_node:  # Node name required before ros__parameters
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    odom0: /wheel_encoder_odom
    odom0_config: [true, true, false, false, false, true]
    odom0_queue_size: 10
    odom0_nodelay: true
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

