<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define materials -->
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/> <!-- Gray color -->
  </material>

  <material name="blue">
    <color rgba="0.0 0.0 1.0 1.0"/> <!-- Blue color -->
  </material>

  <!-- Robot dimensions and properties -->
  <xacro:property name="wheel_radius" value="0.5"/> <!-- Half of diameter 1 -->
  <xacro:property name="wheel_separation" value="1.2"/> <!-- Distance between wheels on opposite sides of base -->
  <xacro:property name="robot_length" value="2.0"/> <!-- Robot length -->
  <xacro:property name="robot_width" value="1.0"/> <!-- Robot width -->
  <xacro:property name="base_height" value="0.1"/> <!-- Thickness of the base link -->

  <!-- Base link -->
  <link name="base_link">
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${robot_length} ${robot_width} ${base_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <box size="${robot_length} ${robot_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Rear Wheels (left and right) - Motor wheels -->
  <link name="rear_left_wheel">
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="0.2" radius="${wheel_radius}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.2" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="rear_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_left_wheel"/>
    <origin xyz="-0.7 ${-wheel_separation / 2} 0.4" rpy="0 0 0"/> <!-- Positioned on the side and slightly below base -->
    <axis xyz="0 0 1"/>
  </joint>

  <link name="rear_right_wheel">
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="0.2" radius="${wheel_radius}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.2" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="rear_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_right_wheel"/>
    <origin xyz="-0.7 ${wheel_separation / 2} 0.4" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Front Wheels (left and right) - Omniwheels -->
  <link name="front_left_omniwheel">
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.05" ixy="0.0" ixz="0.0" iyy="0.05" iyz="0.0" izz="0.05"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="0.2" radius="${wheel_radius}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.2" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="front_left_omniwheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_left_omniwheel"/>
    <origin xyz="0.7 ${-wheel_separation / 2} 0.4" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="front_right_omniwheel">
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.05" ixy="0.0" ixz="0.0" iyy="0.05" iyz="0.0" izz="0.05"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="0.2" radius="${wheel_radius}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.2" radius="${wheel_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint name="front_right_omniwheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_right_omniwheel"/>
    <origin xyz="0.7 ${wheel_separation / 2} 0.4" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Laser (centered on top of base_link) -->
  <link name="laser">
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.02"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.05"/>
      </geometry>
    </collision>
  </link>
  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser"/>
    <origin xyz="0 0 0.55" rpy="0 0 0"/> <!-- Positioned on top of base_link -->
  </joint>

</robot>
